### ISSUE TITLE
Recommendation: TextBar

### ISSUE THREAD

**Issue by richie5um** [nikivdev/flow#10]
Great list, thank you. You might be interested in my app TextBar too. Happy to give you a free license if you would like. 

http://richsomerfield.com/apps/textbar/

**Comment by nikivdev** [comment]
Hey @richie5um 

This seems like a useful app however I currently use [BitBar](https://github.com/matryer/bitbar) for this task which is free and open source. Is there a difference between TextBar and BitBar?

I would love to try it though, thank you for the generous offer.

**Comment by richie5um** [comment]
There are slightly more capabilities in TextBar, but BitBar is a great free alternative that works really well.

The offer still stands if you want to give it a try. 

Thanks.

**Comment by nikivdev** [comment]
I would love to try it. My email is [here](mailto:nikita.voloboev@icloud.com). Thank you. 💛

**Comment by richie5um** [comment]
Do you have a good email address to send the license to?

I'm at rs@richsomerfield.com 

Rich
