### ISSUE TITLE
Culrs Mac App

### ISSUE THREAD

**Issue by iamarnob** [nikivdev/flow#100]
Would like to submit my newly launched mac app on your repository.

Culrs mac app is a thoughtfully crafted color palette tool which sits on your mac menu bar. Culrs have been reimagined from a web app into a mac app to simplify and accelerate the process of choosing colors for your design. They are still the same, but new!

The same color palettes you love on Culrs web app (https://culrs.com/#/) will now be nested in your menubar, making it easy to use! Choose any palette from any category for your design, like Monochromatic, Tetradic, Triad and Analogous.

You are just cmd+e away to your culrs mac app 🙌

[https://culrs.app/](https://culrs.app/)

Thoughtfully crafted color palettes now on your mac, you are just cmd+e away!

**Comment by nikivdev** [comment]
Looks great. I use [Sip](https://sipapp.io) currently for this task and quite like it. :)
