### ISSUE TITLE
Keyboard Maestro

### ISSUE THREAD

**Issue by esaruoho** [nikivdev/flow#103]
Hi, there used to be a km folder for keyboard maestro stuff. has that vanished completely?

i'm on the prowl to find new ideas about keyboard maestro, as i'm slowly getting accustomed to it.

Would really appreciate seeing what kinds of macros you had going, @nikitavoloboev

**Comment by nikivdev** [comment]
https://wiki.nikitavoloboev.xyz/macos/macos-apps/keyboard-maestro/km-macros

**Comment by nikivdev** [comment]
will update it with new macros this week
