### ISSUE TITLE
Service Station – Customize your right-click menu to launch app or scripts

### ISSUE THREAD

**Issue by pkamb** [nikivdev/flow#104]
Hello, I'm the developer of the new app [Service Station](https://apps.apple.com/us/app/service-station/id1503136033?ls=1/). Thought I should drop a link.

 > I love finding new awesome tools and apps. If you have a favorite tool or app that you think I missed, please say it.

Service Station is a Finder Extension that allows you to customize the context menu when you right-click on items in Finder. You can set up menu items *per filetype* or using any other filter using Finder smart search predicates.

 - Launch your favorite apps
 - Launch Shell Scripts, Apple Scripts, or Automator Workflows.

It's like a customizable, cleaned up version of the "Open With" and "Services" menu.

It's a modern Finder Extension using the latest Apple extension APIs, so no haxies required and available on the Mac App Store.

Links:

 - [Website](https://servicestation.menu/)
 - [Twitter](https://twitter.com/ServiceStationX)
 - [Mac App Store](https://apps.apple.com/us/app/service-station/id1503136033?ls=1/)
 - [GitHub (support website)](https://github.com/knurling/ServiceStation)

Screenshots:

![screenshot_menus](https://user-images.githubusercontent.com/342355/79808323-549e2b00-8322-11ea-9780-a61dd4ff55d7.png)
![screenshot_text](https://user-images.githubusercontent.com/342355/79808328-5831b200-8322-11ea-9206-cf38f9a4e382.png)
![screenshot_terminal](https://user-images.githubusercontent.com/342355/79808330-58ca4880-8322-11ea-9394-887e656cef6c.png)
![screenshot_scripts](https://user-images.githubusercontent.com/342355/79808331-5962df00-8322-11ea-87c2-522366c07cd8.png)
![screenshot_image_light](https://user-images.githubusercontent.com/342355/79808985-3c2f1000-8324-11ea-8276-08b5536e0310.png)

**Comment by nikivdev** [comment]
Looks nice, I added it to [macOS apps list](https://github.com/learn-anything/macos-apps#readme). I don't need to use it as I do everything from keyboard so no need for right click menus, also it only applies to Finder.
