### ISSUE TITLE
Notion

### ISSUE THREAD

**Issue by corroc** [nikivdev/flow#105]
Love your site! Gave myself an excellent lunchtime distracting trying some new apps you put me on to. Have you heard of Notion? I think you'd get a lot out of it.
Cheers!

**Comment by nikivdev** [comment]
Yeah I use it. Will update the readme with the tool. 🙂

**Comment by corroc** [comment]
Very curious how a clearly organized person like yourself uses it. Looking forward to the readme!

Cory
