### ISSUE TITLE
How dare you insult the high standard set by mac os software while flaunting subpar streaming services with inferior quality.

### ISSUE THREAD

**Issue by sam1rm** [nikivdev/flow#107]
Tidal masters is the way to enjoy music. +bonus if you know your way around visualizers on a mac [minimally retina]. 

With .flac files & masters audio, your MAX 320 kbps streaming via Spotify vs Tidal -- is like 480p to a 4k monitor [the same music you listen to is easily 100mb, sometimes 400mb]. Just spend $10/month extra AFTER you try it for free. If you don't like it, I don't believe you tried it. Not a tip, but a prescription. 

To be frankly honest, juxtaposing spotify [as of today] with all these awesome tools is absolutely oxymoronic. Don't tell me you pay $10 for 480p pixellated music. 

Most importantly, thanks for posting some great tools and I am excited to check them out when the time is right. 

-⚡️

**Comment by nikivdev** [comment]
I use Spotify not for its sound quality but for discovering new music. Didn't know Tidal music quality is better. Will check it out.

**Comment by securingmom** [comment]
For some contrast:
https://hackaday.com/2021/04/21/mythbusting-tidals-mqa-format-how-does-it-measure-up/

> MQA is not lossless
> MQA not often sources from high sample rate
> MQA adds distortion

**Comment by sam1rm** [comment]
@securingmom great points. However, all streaming services but tidal are 320kbps. Tidal has both Hifi [1440kpbs] and then Masters [apparently not lossless].

I'm not saying I don't agree you with you. However, there aren't any comparable options to Tidal atm. That may change of course. 

@nikitavoloboev what do you think?

**Comment by nikivdev** [comment]
@sam1rm I still love Spotify, also read they are introducing some 'better audio' for more money offering, maybe that will tie that gap. Don't have opinion on this but I won't change using Spotify to Tidal for some audio improvements (personal pref).

https://hackaday.com/2021/04/21/mythbusting-tidals-mqa-format-how-does-it-measure-up/ was a nice link.

**Comment by sam1rm** [comment]
Yawns. Let's cycle back in a year or so.

**Comment by sam1rm** [comment]
It's like your great awesome, well-invested headphones have completely gone to waste.
