### ISSUE TITLE
Alfred, Raycast & others

### ISSUE THREAD

**Issue by matru** [nikivdev/flow#113]
I've read this section on the wiki:

https://wiki.nikiv.dev/tools/raycast

Seems like you are thinking about switching from Alfred?

You do seem to have an extensive workflow config with Alfred, what observations have you made to inspire a switch? Alfred also has a very longstanding and rich community which at least the last two lack, so it seemed interesting point of view. Raycast is very powerful though. Anyways, just wanted to hear your thoughts, as I am just now picking a launcher since I recently switched to a Mac, and would like to invest myself into something just right, the Alfred cost doesn't matter in this case.

Thanks for all the contributions you've made.

**Comment by nikivdev** [comment]
I didn't yet switch to raycast so can't comment on this. I still use Alfred more.

**Comment by spearkkk** [comment]
Aflred is still worthy...

**Comment by youtextme** [comment]
On the Alfred vs Raycast choice in your wiki: a practical path is run **both free** for a week. Raycast’s free tier covers clipboard history + snippets + most extensions; Powerpack/Pro only if you hit a paid-only workflow. No need to rip Alfred out on day one.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
