### ISSUE TITLE
Recommendation: Charles

### ISSUE THREAD

**Issue by fpillet** [nikivdev/flow#12]
In addition to Paw to test your web requests, Charles (https://www.charlesproxy.com) is a must-have complement to monitor what's going on. Can't live without it.

**Comment by nikivdev** [comment]
Thank you. I have heard of Charles before but never did take a look at it in depth. Will do though. 🙂

**Comment by cabello** [comment]
@fpillet @nikitavoloboev how would you compare them to Postman, why [Postman](https://www.getpostman.com/) does not suffice your needs?

**Comment by fpillet** [comment]
@cabello It's not the same kind of product. It's a proxy that intercepts and logs everything, more akin to Wireshark but oriented towards web requests. Have you tried Charles?
