### ISSUE TITLE
recommend: spectacle

### ISSUE THREAD

**Issue by skibz** [nikivdev/flow#13]
can't really do much better than this app for tiling window management.
every alternative i've found is not gratis.

**Comment by nikivdev** [comment]
I have tried Spectacle and it is quite nice. However BetterTouchTool and [this Alfred workflow](https://github.com/untoldwind/alfred2-layout) does everything I need. So there is no need for me to keep another app running in the background. 🙂

**Comment by chavunt** [comment]
asd

**Comment by chavunt** [comment]
asd

**Comment by chavunt** [comment]
asd
