### ISSUE TITLE
Recommended tiling window manager

### ISSUE THREAD

**Issue by slifin** [nikivdev/flow#17]
https://github.com/koekeishiya/kwm
https://github.com/koekeishiya/chunkwm

I've found these a lot more powerful than bettertouchtool, but they do require a bit of setup and exploration of docs to get working nicely, I'd suggest setting up a hyper key to help find space for some of the window tiling binds

**Comment by slifin** [comment]
I've also included kwm (which is the older project) because it has quick workspace switching where chunkwm does not see this issue here: https://github.com/koekeishiya/chunkwm/issues/127

We believe it could be solved by the author of TotalSpaces2 but I think the issue needs a bit more attention before the author might offer the solution

**Comment by soenkekluth** [comment]
https://cordlessdog.com/stay/

**Comment by timkpaine** [comment]
https://github.com/sdegutis/mjolnir

**Comment by nikivdev** [comment]
Thank you guys for the interesting options. I am quite happy with BetterTouchTool still though. 🙂
