### ISSUE TITLE
Similar repo

### ISSUE THREAD

**Issue by mykolaharmash** [nikivdev/flow#18]
Hi there, awesome list!

I have a similar repo, maybe you'll find something useful there. 
https://github.com/nik-garmash/works-for-me

**Comment by nikivdev** [comment]
Hey @nik-garmash 

This looks really awesome. It's a great idea. Reminds me of [this site](https://usesthis.com). 

But here I suppose anyone can propose to add their 'setup'. 🙂

**Comment by mykolaharmash** [comment]
Exactly, like a collaborative collection of cool setups.

**Comment by nikivdev** [comment]
I added your site to a new section of Similar Setups [here](https://github.com/nikitavoloboev/my-mac-os#-similar-setups-). 🙂
