### ISSUE TITLE
SF Command

### ISSUE THREAD

**Issue by rubemz** [nikivdev/flow#21]
Your [Desktop Screenshot](https://github.com/nikitavoloboev/my-mac-os#-desktop-screenshot-) shows an `sf` command that lists some of your mac configurations. Is that a custom script?

**Comment by nikivdev** [comment]
it's an alias for [ScreenFetch](https://github.com/KittyKatt/screenFetch) 🙂

**Comment by rubemz** [comment]
nice! thanks @nikitavoloboev
