### ISSUE TITLE
VS Code question

### ISSUE THREAD

**Issue by voipmeister** [nikivdev/flow#25]
Hi @nikitavoloboev 

Thanks for compiling this great list. I have a question about VS Code. Unlike Atom, VS Code won't let you add multiple project folders in the same window. 

Have you worked around this issue, or is this not an issue for you at all?

Regards!

**Comment by nikivdev** [comment]
I use [this workflow](https://github.com/deanishe/alfred-repos) to launch and switch between my projects. Everything is version controlled so it catches everything. 🙂 

So I don't use multiple projects in same VS Code instance, I have multiple windows if need be.

**Comment by voipmeister** [comment]
Thanks, that explains it.  I'll look into that :)
