### ISSUE TITLE
Terminal theme?

### ISSUE THREAD

**Issue by ghost** [nikivdev/flow#27]
Hey,

Thanks for the very thorough guide. I've found some useful apps that I had no idea existed before.

I am, however, mostly stunned by the way your terminal looks. It seems like you're using iTerm 2 and the utility you're using to display that information is screenFetch - but what about the theme? Can you share any config files, settings etc. to achieve that look? I'm jealous, as you can see.

Thanks in advance.

**Comment by nikivdev** [comment]
Hey,

I use a theme [from here](https://github.com/chriskempson/base16-iterm2). 

base16-3024-dark.
