### ISSUE TITLE
Recommendation: Franz

### ISSUE THREAD

**Issue by JPeer264** [nikivdev/flow#29]
A very nice list!

As you use `Slack` and `Telegram` separately you might be interested in [Franz](http://meetfranz.com/) - you just need one app and you can switch between messenger platforms.

**Comment by huyz** [comment]
Franz is useful.  I use it every day.  But it hasn't been maintained in over a year.  It crashes on silly little things like certain keystrokes.

**Comment by nikivdev** [comment]
I have tried Franz for a bit and disliked it. I only keep telegram, slack and textual as far as text apps go and I am quite happy with it. 🙂
