### ISSUE TITLE
Quiver The Programmer's Notebook

### ISSUE THREAD

**Issue by resting** [nikivdev/flow#32]
I use Evernote for 90% of the time, but Quiver is really good at taking notes with code.
It supports GitHub fenced code blocks, syntax highlighting, tables, and when all else fails, HTML.
Checkout it http://happenapps.com/

update: Just found out Snippetslab does pretty much the same thing 😄 . Nice.

**Comment by nikivdev** [comment]
I actually used it before and quite liked it cells feature. However SnippetsLab does what I need perfectly well and it has a really awesome alfred workflow to query the database so I use it. 

I also disliked the UI of Quiver.

**Comment by resting** [comment]
I see. Good to know you've tried it.
Haven't tried Snippetslab but I'll give it a shot. 
Fragments seems helpful, cause sometimes I find my notes get too long and there wasn't a way to collapse the cells in Quiver.
Think the Gists and Menubar/Alfred integration is nice too.

**Comment by nikivdev** [comment]
I don't actually use fragments. I do use notes and sometimes tags. But I keep everything in one group and sort with prefixes. Thus I can go to any one snippet from Alfred in seconds. 🙂

**Comment by resting** [comment]
Right. Good idea on prefixing. Will try it out and get a feel of it 👍

**Comment by resting** [comment]
So after trying SnippetsLab for a while, there're some things that I miss from Quiver.
Vim mode editing and the ability to export as PDF or HTML (when I want to share with others who doesn't have a markdown viewer).
I guess the Quiver is better suited for documentation and SnippetsLab for snippets.
