### ISSUE TITLE
Remove Spotifree recommendation

### ISSUE THREAD

**Issue by albertorestifo** [nikivdev/flow#35]
I'd like to have a discussion about the Spotifree recommendation.

> Dislike ads and Spotify Membership although very useful does not give me a reason to switch from free version

I too dislike ads. I love Reddit. I could easely block ads on Reddit. Instead, they provide me with the option to buy "Gold" and remove ads. And that's what I do. I buy reddit gold to remove ads I don't like having.

Same goes for Spotify. They provide a way to remove advertisment. I don't find ethical to recommend people to bypass the system instead.

For personal reasons one might not be able to afford the Spotify membership, just like one might not be able to afford Reddit Gold. All I'm saying is maybe to avoid recommending people to do the same.

**Comment by nikivdev** [comment]
You are right and I definitely agree with you on it. I have removed it.
