### ISSUE TITLE
Neofetch replacing Screenfetch

### ISSUE THREAD

**Issue by Axel-Jacobsen** [nikivdev/flow#37]
[Neofetch](https://github.com/dylanaraps/neofetch) is quite customizable, and much faster than `ScreenFetch`. Have tried both and `Neofetch` is ahead by a decent margin.

See: [Neofetch vs Screenfetch](https://github.com/dylanaraps/neofetch/wiki/Neofetch-vs-Screenfetch)
 
Thoughts?

Thanks!

**Comment by nikivdev** [comment]
Yeah you are right, it is better. I will use it now for this kind of thing. 🙂
