### ISSUE TITLE
Typinator snippets

### ISSUE THREAD

**Issue by gubler** [nikivdev/flow#38]
Do you have a list of your (public) Typinator snippets? I really like the look of your snippets for date/time expansion from your Fantastical article on Medium and was wondering if those were publicly available?

(or did I miss a link to them in the article?)

**Comment by nikivdev** [comment]
[Here](https://www.dropbox.com/sh/cv9b8xfaf0mm7os/AABWjO5dzZZnbEP7gpsa0aGUa?dl=1) is the Typinator set I use for Fantastical. 

I actually cut down quite a lot of my Typinator use into KM palettes that look like these : 

![2017-09-03 at 17 42](https://user-images.githubusercontent.com/6391776/30004430-4ceaba60-90cf-11e7-803f-a3dceade3a7e.png)

I then activate them with a hotkey and type a letter and text is inserted : 

![2017-09-03 at 17 43](https://user-images.githubusercontent.com/6391776/30004433-5ca0d21e-90cf-11e7-86ab-5a546d00f4f0.png)

I also have one for emojis : 

![2017-09-03 at 17 43](https://user-images.githubusercontent.com/6391776/30004436-781fc7fc-90cf-11e7-839b-f1223ef1d744.png)

And many more such as entering some personal details (address, emails, mobile number) and various code markdown code blocks.

I will write an article on how I use KM palettes soon though. 🙂 

Hope you like the Fantastical Typinator set, I use that one a lot.
