### ISSUE TITLE
1Password Alternative (and OSS)

### ISSUE THREAD

**Issue by t0lkim** [nikivdev/flow#39]
This popped up on our internal groups the other week:

    https://bitwarden.com/
    https://github.com/bitwarden

I've not looked at it much yet, but could be a sound replacement for 1Password.

**Comment by stefnats** [comment]
Came to my mind, too. KeePass / [KeeWeb](https://github.com/keeweb/keeweb) would be another alternative (OSS)

**Comment by nikivdev** [comment]
Bitwarden sounds interesting although I am quite happy with 1Password thus far. 🙂
