### ISSUE TITLE
Desktop wallpaper and bash PS1?

### ISSUE THREAD

**Issue by thormengkheang** [nikivdev/flow#41]
Hello I love your desktop wallpaper and the way your terminal look? can you share the terminal theme and are using bash? if so can you share your PS1 as well? :)

**Comment by nikivdev** [comment]
[Here](https://transfer.sh/i8Xfj/photo-1462903004115-f8e27d6a3985.jpeg) is the wallpaper.

And [here](https://github.com/nikitavoloboev/my-mac-os/issues/27) I answered what theme I use.

Not sure what you mean by PS1. 🙂

**Comment by thormengkheang** [comment]
oh you’re using zsh shell not bash shell 
![18f2d642-54aa-4fe7-b7b2-ee41676fc18c](https://user-images.githubusercontent.com/8617506/30159518-0cf0b136-93f3-11e7-85ec-459227179d34.jpeg) in the picture above that’s not a default PS1 in bash shell not sure about zsh but we can customize in .bash_profile file

**Comment by thormengkheang** [comment]
I might jump ship to zsh too are you using oh-my-zsh? can you share your zsh setup? 🙃

**Comment by nikivdev** [comment]
I am not using oh-my-zsh. All of my setup is in [my dotfiles](https://github.com/nikitavoloboev/dotfiles). I also wrote an [article](https://medium.com/@NikitaVoloboev/pretty-and-fast-shell-97ea870f2805) you might like to read on how I customise my shell. 🙂

**Comment by thormengkheang** [comment]
I see many thank 🙃

**Comment by huyz** [comment]
Don't use oh-my-zsh. This one is much better: https://github.com/sorin-ionescu/prezto
