### ISSUE TITLE
Recommendation for BitBar

### ISSUE THREAD

**Issue by yqrashawn** [nikivdev/flow#45]
Must say your works great. Found lots of useful apps here.

There's a app called BitBar that run scripts, get their stdout message and print them on menu bar. Which I found really useful for monitoring servers, checking mails, maintaining simple todo list or reminder and all other simple stuffs.
It's api is simple and easy to use. Support tons of languages. It's great if we add it into the list and let others to try it.

You can check it out on its [home page](https://getbitbar.com/).

**Comment by nikivdev** [comment]
Yeah you are right. I actually use it too. Will add it. 🙂

**Comment by nikivdev** [comment]
added it
