### ISSUE TITLE
Password Manager

### ISSUE THREAD

**Issue by jchristgit** [nikivdev/flow#46]
What made you choose 1Password as your password manager? 
I'm currently looking into changing from the default Keychain for various reasons towards an actual password manager. I'm testing out [1Password](https://1password.com/) and [Enpass](https://www.enpass.io) right now, and they seem very similar, apart from some UI differences. However, 1Password uses a subscription model while Enpass costs ["$9.99 / platform"](https://www.enpass.io/pricing/). Did you try out other password managers?

**Comment by nikivdev** [comment]
I have not. I've used 1Password for quite some time now and I have paid once for it so I am not on subscription. 

But yeah, there is a lot of things to like about 1Password such as quick pop up window you get to search passwords, secret notes, keys and other things you have saved.

But if you liked Enpass, go for it. 🙂

**Comment by jchristgit** [comment]
Thanks for your quick reply and thoughts!
