### ISSUE TITLE
iTerm alternative

### ISSUE THREAD

**Issue by yqrashawn** [nikivdev/flow#47]
iTerm is the most competitive terminal emulator on macOS. It's of tons of functionalities. I use it since the day I start using macbook.

Recently found two terminal emulator that both using OpenGL for rendering, which make them really fast. I thought you may want to try.

Alacritty(https://github.com/jwilm/alacritty) written in rust. Use yaml file for configuration. The default configuration file can be checked here. https://github.com/jwilm/alacritty/blob/master/alacritty.yml

Kitty(https://github.com/kovidgoyal/kitty) written in c. Use .conf file for configuration. Can check out here https://github.com/kovidgoyal/kitty/blob/master/kitty/kitty.conf

They are all faster than iTerm but with less functionality (iTerm's really good at this).
I'm trying alacritty right now, cause kitty can't display Chinese character easily. And alacritty's author is currently using it on macOS while kitty aiming more on linux.

Think you may want to try.

**Comment by nikivdev** [comment]
Thank you @yqrashawn 

I will definitely look into them more. Currently I am hooked to iTerm though and [this workflow for it](https://github.com/isometry/alfred-tty). 🙂

**Comment by yqrashawn** [comment]
@nikitavoloboev I tried that. It's great, but can't fit in my workflow, cause I'm used to using tmux.
I'll close the issue.
