### ISSUE TITLE
Pixave backup to imgur - Automation ?

### ISSUE THREAD

**Issue by salmanulfarzy** [nikivdev/flow#50]
Do you prefer any tools to upload Pixave images to imgur ?

**Comment by nikivdev** [comment]
I use [this](https://aptonic.com) and drag and drop image to the Imgur action : 

![2017-11-08 at 15 06](https://user-images.githubusercontent.com/6391776/32553169-6003a314-c496-11e7-92ea-59154f9f9958.png)

For maintaining my Imgur library, I simply open the Imgur album and add the image to the end of it. I also use [this workflow](https://github.com/nikitavoloboev/small-workflows#useful-file-actions) to quickly copy image from Pixave to Desktop. 🙂
