### ISSUE TITLE
neofetch

### ISSUE THREAD

**Issue by onedr0p** [nikivdev/flow#58]
I came across neofetch and it seems to be a lot faster and has more customization.

https://github.com/dylanaraps/neofetch

Here's a breakdown of Screenfetch vs. Neofetch:

https://github.com/dylanaraps/neofetch/wiki/Neofetch-vs-Screenfetch/f07119fb9854f5b2c4e40574aebcb41fa4e14806

**Comment by nikivdev** [comment]
Thank you. Will use neofetch instead.
