### ISSUE TITLE
Homebrew isn't on the list

### ISSUE THREAD

**Issue by Lillecarl** [nikivdev/flow#6]
Your list is broken, if Homebrew isn't on a "nice mac apps" list, then the list is automagically invalidated.

Cakebrew is nice for those who likes gui.

**Comment by nikivdev** [comment]
Oh my bad, yeah I forgot to mention it.

This list goes over applications and homebrew is a package manager. But I ill create a CLI section and include it.

Thank you.

**Comment by nikivdev** [comment]
Added it [here](https://github.com/nikitavoloboev/my-mac-os#command-line-apps-). Take a look. 🙂

**Comment by Lillecarl** [comment]
It's better, but there's one thing that needs to be fixed!

"Homerew is a really wonderful and user friendly package manager for macOS."
"Homebrew is a really wonderful and user friendly package manager for macOS."

While we're at it ;)
