### ISSUE TITLE
Add stronghold?

### ISSUE THREAD

**Issue by alichtman** [nikivdev/flow#60]
I wanted to suggest adding a MacOS CLI security tool I developed to the list.

Check it out, and let me know if I should open a PR with the suggested changes!

https://github.com/alichtman/stronghold

**Comment by nikivdev** [comment]
Hey @alichtman, sorry I haven't had the chance to check out the app. It looks awesome however I am still running El Captain. I will check it soon. 🙂

**Comment by alichtman** [comment]
Any update on this?

**Comment by nikivdev** [comment]
Thank you @alichtman. Finally got a new mac and HS to test this and it looks awesome.

I'm not currently in need of such app however.
