### ISSUE TITLE
Recommendation: Magnet window manager

### ISSUE THREAD

**Issue by anotterdev** [nikivdev/flow#64]
I just recently found out about the window manager [Magnet](http://magnet.crowdcafe.com/) and figured I would share it here. (It is not a window manager in the classic sense, just an app that helps snapping windows to locations)
The app is simple in what it does, but does it well and effortless in my opinion.

**Comment by nikivdev** [comment]
Thank you. I have tried it but I find [BetterTouchTool](https://folivora.ai) to do everything I need already. So I don't want to run another app. 🙂
