### ISSUE TITLE
What do you use to write to NTFS partitions?

### ISSUE THREAD

**Issue by douglasjunior** [nikivdev/flow#67]
I come from a relentless search for tools (preferably free or opensource) to mount/read/write to NTFS partitions.

The best I've found so far was [Mounty for NTFS](https://mounty.app/). (but I see people saying about the fragility and loss of data)

Do you recommend any solutions?

**Comment by namhokim** [comment]
Tuxera ntfs for mac is useful. But Is need payment.

https://www.tuxera.com/products/tuxera-ntfs-for-mac/

**Comment by nikivdev** [comment]
Don't use NTFS sorry
