### ISSUE TITLE
Recommendation: LICEcap

### ISSUE THREAD

**Issue by BrettGregson** [nikivdev/flow#68]
LICEcap is a (terribly named) macOS tool for capturing an area of your desktop and saving it directly to an animated .GIF

Very handy for when you want to send a quick "video" of your screen via email or on the web. It's something I never thought I needed, but have ended up using a load over the years.

https://www.cockos.com/licecap/

**Comment by nikivdev** [comment]
I use [Kap](https://github.com/wulkano/kap) for that 🙂
