### ISSUE TITLE
Favorite app suggestion

### ISSUE THREAD

**Issue by mu-hun** [nikivdev/flow#71]
# [Muse](https://github.com/xzzz9097/Muse)

> An open-source Spotify, iTunes and Vox controller with TouchBar support, system-wide TouchBar controls (à la iTunes) and Spotify account integration.

This app is useful to control Spotify with TouchBar and keyboard.

I think is more better control provide than [BetterTouchTool Touch Bar Widget](https://docs.bettertouchtool.net/docs/touch_bar_widgets.html).

## Popup window

<img width="387" alt="screen shot 2018-10-02 at 8 34 52 pm" src="https://user-images.githubusercontent.com/5278201/46346344-ad479d80-c682-11e8-9aa4-606729944dfa.png">

Several handy shortcuts are provided when the popup window is open (eg. <kbd>a</kbd> and <kbd>left arrow</kbd> is previous track, <kbd>d</kbd> and <kbd>right arrow</kbd> is toggle next track, <kbd>l</kbd> is likes track.)

## TouchBar

<img width="1085" alt="touch bar shot 2018-10-02 at 8 55 35 pm" src="https://user-images.githubusercontent.com/5278201/46347173-95bde400-c685-11e8-84e1-9f2038771846.png">

<img width="1085" alt="touch bar shot 2018-10-02 at 8 56 39 pm" src="https://user-images.githubusercontent.com/5278201/46347234-ce5dbd80-c685-11e8-8c10-c0715c8be81a.png">

<img width="1478" alt="screen shot 2018-10-02 at 9 43 25 pm" src="https://user-images.githubusercontent.com/5278201/46349204-5e9f0100-c68c-11e8-8ba9-57b2dcf7dabc.png">

## MenuBar

<img width="446" alt="screen shot 2018-10-02 at 9 39 30 pm" src="https://user-images.githubusercontent.com/5278201/46348967-b1c48400-c68b-11e8-8fb6-9424c29dbda3.png">

You can view song title in menu bar.

**Comment by nikivdev** [comment]
Cool app but I just use Alfred & [Spotify workflow](https://github.com/vdesabou/alfred-spotify-mini-player)
