### ISSUE TITLE
Recommendation: Typora

### ISSUE THREAD

**Issue by behroozk** [nikivdev/flow#76]
Hi,

I came across your repo and first of all I want to say kudos! 🙏 I learned about several good apps and couple of better alternatives to what I currently use.

One recommendation I have is [Typora](https://typora.io) for working with markdown files and projects. It has many features including file organization, themes, import/export to several file types, syntax highlighting, diagrams, and etc. It's also free while it's in beta stage.

I have used Marked before and find Typora more user friendly. I recommend you give it a try.

Again, thanks for the awesome repo!

**Comment by keehun** [comment]
I also love Typora! Only problem is that it does not yet seem stable. Crashes are not often but regular enough to be noticed.

**Comment by nikivdev** [comment]
thanks for suggestion but I use Sublime Text & Ulysses for writing
