### ISSUE TITLE
Affinity Designer and Affinity Photo

### ISSUE THREAD

**Issue by ghost** [nikivdev/flow#8]
I agree with almost all your recommendations. There are only two great alternatives (or complements) to Sketch and Pixelmator that you can try:
* Affinity Designer (for vector / UI design) — https://affinity.serif.com/en-us/designer/
* Affinity Photo (photo editing) — https://affinity.serif.com/en-us/photo/

There were some apps I didn't know of — Thank you very much for this initiative!

**Comment by nikivdev** [comment]
Hey @andylima 

I agree, Affinity Photo and Affinity Designer are quite awesome apps. I only tried Affinity Photo briefly and liked it. 

I will update the list quite soon too as its a bit outdated.

**Comment by ghost** [comment]
> I will update the list quite soon too as its a bit outdated.

Oh. Looking forward to the updates then!  🎉

**Comment by nikivdev** [comment]
I am still evaluating Affinity Photo but when I do, I think I will add it here. Thank you for bringing my attention to it. 🙂
