### ISSUE TITLE
Are you using the Macos mojave version?

### ISSUE THREAD

**Issue by gongzili456** [nikivdev/flow#84]
This version has white border out window, it's ugly. I have regretted upgrading now.

like this:

<img width="720" alt="wx20181005-231622 2x" src="https://user-images.githubusercontent.com/6082335/46543910-b049c480-c8f4-11e8-98f5-42edbcee677a.png">

**Comment by nikivdev** [comment]
It’s not the best. But it’s better than before and pure white windows.
