### ISSUE TITLE
Improve Textual Theme

### ISSUE THREAD

**Issue by nikivdev** [nikivdev/flow#87]
- [x] Hide `Disconnected for Sleep Mode` messages
- [x] Hide `Current Session` messages & darken the font so it's not too in your face
- [ ] Centre date stamps (i.e. `10 October 2018`). Remove White borders around it. Style it nicely (grey text like Discord). There is a TODO in the CSS file. Must have very small font. Do I even need the day stamps?
- [x] Remove seconds from time stamps. Only have `[Hour:Minute]`. 

In the end only time stamps and messages should be shown. Everything else is noise.

**Comment by rsprudencio** [comment]
Hi, I couldn't find anywhere but how did you hide Disconnected for Sleep Mode messages?
