### ISSUE TITLE
Recommendation: Magnet and Paste

### ISSUE THREAD

**Issue by alexcamlo** [nikivdev/flow#9]
I think these two apps would fit really good in your workflow

[Magnet](http://magnet.crowdcafe.com): To keep your workspace windows organised
[Paste](http://pasteapp.me): Stores everything you copy across all your Macs and extends clipboard capacity up to unlimited.

**Comment by nikivdev** [comment]
Hey @thewinger 

I tried Magnet before but for my use cases BetterTouchTool is enough so I don't want another app running in the background.

And for Paste, I used that before and loved it but recently found that Alfred's clipboard manager is a lot faster than Paste so I switched to it. 🙂

**Comment by ghost** [comment]
If you want Serial Paste, Search, Last nn Shortcuts then this is the best clipboard manager I've found (after having tried many, many of them) — [CopyLess](https://copyless.net/).

**Comment by nikivdev** [comment]
I am quite happy with Alfred. It's super fast and does what I need already. 🙂
