### ISSUE TITLE
monokai night iterm colors

### ISSUE THREAD

**Issue by caarlos0** [nikivdev/flow#92]
Hi, thanks for presenting me to the Monokai Night theme, it's awesome!

About the itermcolors, my OCD hit me when I saw that the colors of the terminal inside vscode using monokai night were different from the ones in iterm using monokai night... I found out that some of the colors differ, so, I've copied the terminal theme colors from the vscode theme:

```
    "terminal.ansiBlack": "#333333",
    "terminal.ansiBlue": "#6a7ec8",
    "terminal.ansiBrightBlack": "#666666",
    "terminal.ansiBrightBlue": "#819aff",
    "terminal.ansiBrightCyan": "#66d9ef",
    "terminal.ansiBrightGreen": "#a6e22e",
    "terminal.ansiBrightMagenta": "#ae81ff",
    "terminal.ansiBrightRed": "#f92672",
    "terminal.ansiBrightWhite": "#f8f8f2",
    "terminal.ansiBrightYellow": "#e2e22e",
    "terminal.ansiCyan": "#56adbc",
    "terminal.ansiGreen": "#86b42b",
    "terminal.ansiMagenta": "#8c6bc8",
    "terminal.ansiRed": "#c4265e",
    "terminal.ansiWhite": "#e3e3dd",
    "terminal.ansiYellow": "#b3b42b",
    "terminal.background": "#262626",
    "terminal.border": "#161616",
    "terminal.foreground": "#dddddd",
    "terminal.selectionBackground": "#ffffff24",
    "terminalCursor.background": "#262626",
    "terminalCursor.foreground": "#f2f2f2",
```

into my own monokai night theme.

Terms look equal now on both iterm and vscode:

![image](https://user-images.githubusercontent.com/245435/51549734-1df11080-1e52-11e9-967f-ecad4a62f40d.png)

![image](https://user-images.githubusercontent.com/245435/51549757-29443c00-1e52-11e9-842a-f1376c8e5c15.png)

if it interests you, I can open a PR... in any case, here is the link: https://github.com/caarlos0/macOS/blob/master/Monokai%20Night.itermcolors

Cheers!

**Comment by nikivdev** [comment]
> if it interests you, I can open a PR

Please do ❤️

**Comment by nikivdev** [comment]
Although I quite like `#1F1F1F` as background. Same as editor. And I switch between iTerm/VSCode often.

**Comment by nikivdev** [comment]
That's the only change I'd make to your theme to make it perfect for me. So if you do a PR, I'll only change the background to `#1F1F1F` and merge.

**Comment by caarlos0** [comment]
![image](https://user-images.githubusercontent.com/245435/51550575-c653a480-1e53-11e9-86f2-8c6bbce3114a.png)

Looks the same for me haha

the tree on vscode has a darker background though...
